### PR TITLE
Wrap reading service's initialState in service scope

### LINKED ISSUE #757: Spawning machines on entry action doesn't work (4.7.0-rc5)
**Description**
I've been playing around with the next release of xstate and the new features are looking great. One issue I've noticed is spawning machines on an entry action doesn't seem to be working.

**Expected Result**
Spawning a machine in an assign action should create a machine and save it as a ref in context.

**Actual Result**
Xstate gives a warning about spawning new machines outside of an assign and doesn't spawn the machine.

**Reproduction**
https://codesandbox.io/s/hopeful-franklin-8z0t6

**Additional context**
Create with 4.7.0-rc5

### PR DESCRIPTION
**Pull request by Andarist**
Fixes #757

### CODE REVIEW

**Comment by derek-duncan** [comment]
I'm not sure if this is the complete fix for #757. I'm seeing `spawn` return an Actor and immediately an Interpreter which may be fundamentally causing this issue. See the explanation here https://github.com/davidkpiano/xstate/issues/772#issuecomment-551890910.

**Comment by Andarist** [comment]
Have you tried applying this fix to your repro? Could you prepare an exact repro case for the reported problem with a clear list of steps to reproduce? I'm not having much time lately so everything that helps me to jump **directly** into debugging/fixing problems is a huge help 🙏

**Comment by derek-duncan** [comment]
@Andarist Sorry for the inconvenience, I pulled this branch down and it fixes the issue! Good work!

**Comment by Aleksion** [comment]
@Andarist @davidkpiano  I've noticed that all the code sandboxe exampels above - it also happens OCCASIONALLY when I use actors myself - throw this warning:

```
index.js:27 Warning: Attempted to spawn an Actor (ID: "(machine)") outside of a service. This will have no effect.
```

any idea why?

**Comment by Andarist** [comment]
@Aleksion hard to tell - could you prepare a repro case and report a new issue?

**Pull request merged**
