### PR TITLE
@xstate/react: add context option for convenience

### PR DESCRIPTION
**Pull request by hnordt**
Compilation will fail due to `UseMachineOptions` warning.

As I don't know TS, I'll need help to fix it.

cc @davidkpiano @Andarist

### CODE REVIEW

**Comment by davidkpiano** [comment]
Can you share the compilation error here?

**Comment by Andarist** [comment]
You can fix errors by applying this patch:
```
diff --git a/packages/xstate-react/src/index.ts b/packages/xstate-react/src/index.ts
index 2d16e28..f862040 100644
--- a/packages/xstate-react/src/index.ts
+++ b/packages/xstate-react/src/index.ts
@@ -20,14 +20,14 @@ interface UseMachineOptions<TContext> {
   immediate: boolean;
 }
 
-const defaultOptions: UseMachineOptions = {
+const defaultOptions = {
   immediate: false
 };
 
 export function useMachine<TContext, TEvent extends EventObject>(
   machine: StateMachine<TContext, any, TEvent>,
   options: Partial<InterpreterOptions> &
-    Partial<UseMachineOptions> &
+    Partial<UseMachineOptions<TContext>> &
     Partial<MachineOptions<TContext, TEvent>> = defaultOptions
 ): [
   State<TContext, TEvent>,
@@ -46,7 +46,7 @@ export function useMachine<TContext, TEvent extends EventObject>(
     {
       ...machine.context,
       ...context
-    }
+    } as TContext
   );
 
   // Reference the service
```

**Comment by hnordt** [comment]
Thank you very much @Andarist!

**Comment by davidkpiano** [comment]
Can you write a test for this? You can do this in `/packages/xstate-react/test` and run `npm t` in this directory.

**Comment by hnordt** [comment]
I added a test, but it's failing to TS errors. 😡

```js
    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    test/useMachine.test.tsx:114:48 - error TS2345: Argument of type '{ context: { test: boolean; }; }' is not assignable to p
arameter of type 'Partial<InterpreterOptions> & Partial<UseMachineOptions<{ data: undefined; }>> & Partial<MachineOptions<{ da
ta: undefined; }, EventObject>>'.
      Type '{ context: { test: boolean; }; }' is not assignable to type 'Partial<UseMachineOptions<{ data: undefined; }>>'.
        Types of property 'context' are incompatible.
          Property 'data' is missing in type '{ test: boolean; }' but required in type '{ data: undefined; }'.

    114       const [state] = useMachine(fetchMachine, { context });
                                                       ~~~~~~~~~~~

      test/useMachine.test.tsx:17:5
        17     data: undefined
               ~~~~~~~~~~~~~~~
        'data' is declared here.
```

**Comment by davidkpiano** [comment]
I'll fix it.

**Pull request merged**
