### PR TITLE
Add test for accessing stateGuard.state in a conditional expression of the choose action creator

### PR DESCRIPTION
**Pull request by CodingDive**
Reproduces #1144

### CODE REVIEW

**Comment by Andarist** [comment]
Are you sure this doesn't just work for actions defined on the initialization path? `choose` uses the same `evaluateGuard` as conditional transitions and it seems that this should be provided:
https://github.com/davidkpiano/xstate/blob/401413e30110c73cd2b252b41c4f5488ae0f685d/packages/core/src/utils.ts#L681
unless we are talking about `choose` actions executed before the first `state` object has a chance to get created.

**Comment by CodingDive** [comment]
I see. I was just testing the init path I believe. I didn't know the
machine is missing state when initizializing but it makes sense that the
first state is only available after all the transient transitions have been
resolved and the entry actions executed.

I'll take a look at this tonight and will change the test accordingly.

**Comment by CodingDive** [comment]
Yes, you are right. The test is now passing after checking the non-initialization path. Thank you! 😊

**Comment by davidkpiano** [comment]
Well, more tests can't hurt ➕

**Pull request merged**
