### PR TITLE
Typo: ; as separator for object props instead of ,

### PR DESCRIPTION
**Pull request by chrismatheson**

### CODE REVIEW

**Comment by Andarist** [comment]
Actually both separators are allowed:
https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAglC8UDeUBmB7dAuKBnYATgJYB2A5gDRQBGAhgTiQK4C21EBUAvgFCiRQAQgmRpMOfMXIBuGrQBejVu068eAY3Ql8UWnpEAKemRwwAlAgB8yHlDu6CZAHR0CPNZu3Aa1aoeM4ghbw1ki29sYuCu5AA

**Comment by chrismatheson** [comment]
@Andarist yeah sorry i was a bit quick on this one, just reading the rest of the code its a consistent thing. Just curious if there was a specific reasoning behind the choice? Ive written & read a lot of TS recently and this is the first time I've come across it :)

**Comment by Andarist** [comment]
No idea, might be @davidkpiano preference, or just Prettier auto-formatting.

**Comment by davidkpiano** [comment]
Prettier also formats it to `;` in the project; semicolons are preferred by `tslint` for interfaces as well.

**Pull request closed without merging**
