### PR TITLE
Tweaked Promise support in interpreter to accept any thenable (aka PromiseLike)

### PR DESCRIPTION
**Pull request by johnyanarella**
* Added `isPromiseLike()` type guard to `utils`.
* Changed invoke/service type requirement from `Promise` to `PromiseLike`.
* Used `Promise.resolve()` to adopt untrusted thenables into trusted Promises.

Related: #412

### CODE REVIEW

**Comment by johnyanarella** [comment]
I haven't done much with Typescript - feel free to let me know if there's something I got wrong here! Ended up leveraging Typescript's built-in `PromiseLike` type.

Still pondering how best to introduce tests for this. Not keen on duplicating the entire "with promises" block, as that explodes the size of the test suite. Thoughts?

One thought I had was to wrap all the Promises in the existing tests with a wrapper that returned a PromiseLike view of them (i.e. just  exposed the `then()` function).

**Comment by davidkpiano** [comment]
This looks good so far! I think your idea of wrapping existing tests would be fine, something like:

```js
describe('with promises', () => {
  // fn is (res, rej) => void
  const createRealPromise = (fn => new Promise(fn));
  const createPromiseLike = (fn => ({ then: /* ... */ })); // fake promise

  [createRealPromise, createFakePromise].forEach(createPromise => {
    // ...
    src: ctx => createPromise(resolve => { ... })

    // ...
    it('existing test etc.', () => {});
  });
});
```

**Comment by johnyanarella** [comment]
Ugh. The indentation level change did a real number on the readability of the diff. 

Worth noting that there were previously a couple callback related tests that were in the promises section, moved the `describe('callbacks', ...` up to wrap those.

**Comment by johnyanarella** [comment]
Also noticed an unrelated parent/child test (ping/pong machines) that looks like it snuck into the middle of the Promises tests. Moved it up and out.

**Pull request merged**
