### PR TITLE
Use pretty-quick instead of lint-staged

### PR DESCRIPTION
**Pull request by FredyC**
A little DX improvement. The `pretty-quick` module is a faster variant of a classic `lint-staged` approach which tends to be fairly slow. 

Immer started using this recently and we switched over to it in MobX as well.

### CODE REVIEW

**Comment by Andarist** [comment]
Thanks for the PR!

I'm not the biggest fan of this change though - I don't see anything, in particular, lacking from the lint-staged and I haven't noticed it being too slow. It gets the job done.

`pretty-quick` also seems focused on running prettier, while `lint-staged` is a more general tool and can be used for other tasks as well.

**Comment by FredyC** [comment]
> while `lint-staged` is a more general tool and can be used for other tasks as well.

Yes, but is it used for other tasks in practice? I haven't seen such a case so far :) You can have both tools alongside anyway if there would be such need in the future.

Up to you. It probably depends on how fast your machine is. Especially on Windows, the difference in speed is fairly noticeable.

**Comment by Andarist** [comment]
> Yes, but is it used for other tasks in practice? I haven't seen such a case so far :)

It's pretty often also used for linting. I also had to generate .md files couple of times as part of the precommit hook.

> You can have both tools alongside anyway if there would be such need in the future.

Right, but they are similar enough that's probably not worth to keep both and coordinate their usage.

**Comment by davidkpiano** [comment]
We will be using `lint-staged` for building documentation as well.

**Comment by FredyC** [comment]
Alright, nevermind then :) I was just excited because it made my committing so fast again :)

**Pull request closed without merging**
