### PR TITLE
Add react Calculator example in the Examples section

### PR DESCRIPTION
**Pull request by GiancarlosIO**
Can we add a react calculator example in the docs? 🤔
This project uses xstate 4.x. I'm still working on the typescript and testing side but the calculator itself is finished.

### CODE REVIEW

**Comment by davidkpiano** [comment]
Seems like the CodeSandbox has some errors?

**Comment by GiancarlosIO** [comment]
@davidkpiano oh god, looks like a bug in the CodeSandbox 🤔 . I'll check it
🏃

**Comment by GiancarlosIO** [comment]
alright, @davidkpiano it's fixed now

**Comment by davidkpiano** [comment]
Thanks! Looks great!

**Pull request merged**
