### PR TITLE
Remove React double import

### PR DESCRIPTION
**Pull request by hosein2398**

### CODE REVIEW

**Comment by davidkpiano** [comment]
Thanks, can you add a quick changeset (patch)?

Run `yarn changeset` at the root. Should be easy from there!

**Comment by hosein2398** [comment]
IDK if I'm right about this. If there's any problem, let me know. 
Thanks

**Comment by Andarist** [comment]
@davidkpiano this is not something that has any impact on end-users so I don't believe this deserves a changeset - it can be freely removed from this PR. It's like a stylistic change - which we wouldn't like to list in our changelogs, right? 😉

**Comment by davidkpiano** [comment]
> @davidkpiano this is not something that has any impact on end-users so I don't believe this deserves a changeset - it can be freely removed from this PR. It's like a stylistic change - which we wouldn't like to list in our changelogs, right? 😉

Sure, that makes sense.

**Pull request merged**
